type : convolutional

learning_rate: 0.000001
batch_size: 100
image_size: [28,28]
dataset_size: 60000
epochs: 2
images_path: "MNIST/train-images.idx3-ubyte"
labels_path: "MNIST/train-labels.idx1-ubyte"