type: convolutional
learning_rate: 1.0e-06
batch_size: 100
image_size:
- 28
- 28
dataset_size: 600
epochs: 100
images_path: MNIST/train-images.idx3-ubyte
labels_path: MNIST/train-labels.idx1-ubyte
leaky_ReLU_alpha: 0.005
runtime: 870
date: 07_12_2025_21-59-32
