type: convolutional
learning_rate: 0.0005
batch_size: 50
image_size:
- 28
- 28
dataset_size: 100
epochs: 100
images_path: MNIST/train-images.idx3-ubyte
labels_path: MNIST/train-labels.idx1-ubyte
leaky_ReLU_alpha: 0.01
runtime: 144
date: 07_15_2025_14-13-00
